### ISSUE TITLE
expand on json encoding/decoding re:dart

### ISSUE THREAD

**Issue by shrugs** [lesnitsky/howtodothisinflutter#20]
json encoding and decoding is famously complicated in flutter because runtime reflection is disabled, so it'd be good to give readers an indication of their different options—[similar to how this page works](https://flutter.io/docs/development/data-and-backend/json)—in order to avoid a situation where someone expects that json is plug-and-play, but then realizes that things are more complicated than they expected.

**Comment by lesnitsky** [comment]
@shrugs thanks, this is completely valid point, will add more details to json example
