### ISSUE TITLE
Rename PureComponent to Stateless Component

### ISSUE THREAD

**Issue by deadcoder0904** [lesnitsky/howtodothisinflutter#21]
In Flutter, stateless component does not have state so it makes sense to change `PureComponent` to `Stateless Component`

So this 

```js
import React from 'react';

type Props = {
  name: string,
};

class Greeter extends React.PureComponent<Props, {}> {
  render() {
    return (
      <View>
        <Text>Hello, {this.props.name}</Text>
      </View>
    );
  }
}
```

becomes

```js
import React from 'react';

type Props = {
  name: string,
};

const Greeter = props => (
      <View>
        <Text>Hello, {props.name}</Text>
      </View>
    );
```

What do you think?

**Comment by lesnitsky** [comment]
@deadcoder0904 Thanks 👍
Initially example contained stateless component, but named "pure" which caused negative feedback on reddit. I've changed stateless component to pure, but probably the best way was to use "stateless" instead of "pure"
