### ISSUE TITLE
The 'type' keyword isn't standard React Native

### ISSUE THREAD

**Issue by rapPayne** [lesnitsky/howtodothisinflutter#27]
You use 'type' in a few places like

`type State = { yada:yada };`

I don't recognize the type keyword in vanilla JavaScript. Is this a Babel feature? If so, can we put that in the explanations? If not, maybe change it to a const?

**Comment by lesnitsky** [comment]
this is flow feature. it is now available out of the box in react native

**Comment by rapPayne** [comment]
The type keyword doesn't work out of the box in react native. All I'm suggesting is that we either fall back to const which is standard or document that type is a flow keyword and tell the users what to do to set flow up. Seems that const would be easier to change and easier for all devs to understand.

**Comment by lesnitsky** [comment]
const has nothing to do with type system. I feel like it is fair to compare RN with flutter with types in mind, as it is important part of development process. I initially was going to add `prop-types` to RN examples, but rn deprecated prop-types in favor of flow. I'll consider adding some notes about flow, but I believe you need just to add `// @flow` comment at the top of the file and it just works. (not sure if .flowconfig` is created by `init`
Also feel free to contribute 😏
